version: '3.1'

services:
  frontend:
    image: nysam/frontend:latest
    ports:
      - "8080:80"

  backend:
      image: nysam/backend:1.0
      ports:
        - "3000:3000"
      depends_on:
        - mongodb
        - mongo-express

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
  
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8000"
    


