version: '3.3'

services:
  frontend:
    image: nysam/frontend:latest
    ports:
      - "8080:80"

  backend:
    image: nysam/backend:1.0
    ports:
      - "5000:5000"
    environment:
      - MONGO_DB_USERNAME=${MONGOD_ADMIN_USER}
      - MONGO_DB_PWD=${MONGOD_ADMIN_PASS}
      - MONGODB_URI=mongodb://mongo:27017/yolo # Update to use service name as hostname
    volumes:
      - backend-data:/backend/app/data  # Mount a volume for backend data
    depends_on:
      - "mongo"
      - "mongo-express"

  mongo:
    image: mongo:8.0.0-rc6-jammy
    restart: always
    ports:
      - "27017:27017"
    environment:
     - MONGO_INITDB_ROOT_USERNAME=${MONGOD_ADMIN_USER}
     - MONGO_INITDB_ROOT_PASSWORD=${MONGOD_ADMIN_PASS}
    volumes:
      - mongodb-data:/data/db  # Mount a volume for MongoDB data

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_URI=mongodb://@mongo:27017/yolo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ADMIN_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ADMIN_PASS}
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_BASICAUTH=false
volumes:
  backend-data:
  mongodb-data: