- name: Setup Yolo
  hosts: webservers
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    frontend_port: 80
    backend_port: 5000
    database_port: 27017


  tasks:
    # - name: Copy project files
    #   copy:
    #     src: .
    #     dest: app/

    - name: Include frontend role
      include_role:
        name: frontend
      tags: [frontend]

    - name: Include backend role
      include_role:
        name: backend
      tags: [backend]

    - name: Include database role
      include_role:
        name: database
      tags: [mongod]
    
  

  roles:
    - test-connectivity 
    - update-cache
    - install-docker 
    - install-dockercompose
    - clone-repo
    - frontend
    - backend
    - database
    - run-docker-compose

    
   




