- name: Setup Yolo
  hosts: webservers
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
 
  roles:
    - test-connectivity 
    - update-cache
    - install-docker 
    - install-dockercompose
    - clone-repo
   

  tasks:
  - name: Copy project files
    copy:
      src: .
      dest: app/

  
  - name: Run docker-compose 
    command: docker-compose up -d 
    args:
      chdir: app/
    become: true 


