- name: Setup Yolo
  hosts: webservers
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    app_source: "https://github.com/MoSam007/yolo.git"
    frontend_port: 80
    backend_port: 5000
    database_port: 27017

  tasks:
  - name: Include frontend role
    include_role:
      name: frontend
    tags: [frontend]

  - name: Include backend role
    include_role:
      name: backend
    tags: [backend]

  - name: Include database role
    include_role:
      name: database
    tags: [mongod]

  roles:
      - test-connectivity 
      - update-cache
      - clone-repo
      - install-docker 
      - install-dockercompose
      - frontend
      - backend
      - database
      - run-docker-compose
